import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

G = nx.DiGraph()
G.add_node(1, color='green', weight=2, rank=0)
G.add_node(2, color='green', weight=2, rank=1)
G.add_node(3, color='red', weight=3, rank=1)
G.add_node(4, color='green', weight=2, rank=1)
G.add_node(5, color='green', weight=1, rank=1)
G.add_node(6, color='green', weight=2, rank=2)
G.add_node(7, color='red', weight=2, rank=2)
G.add_node(8, color='green', weight=1, rank=2)
G.add_node(9, color='red', weight=2, rank=2)
G.add_node(10, color='red', weight=1, rank=3)
G.add_node(11, color='green', weight=1, rank=3)
G.add_node(12, color='green', weight=2, rank=3)
G.add_node(13, color='green', weight=2, rank=3)
G.add_node(14, color='green', weight=2, rank=4)
G.add_node(15, color='red', weight=1, rank=4)
G.add_node(16, color='red', weight=1, rank=4)
G.add_node(17, color='green', weight=1, rank=5)

G.add_edge(1,2)
G.add_edge(1,3)
G.add_edge(1,4)
G.add_edge(1,5)
G.add_edge(2,6)
G.add_edge(2,7)
G.add_edge(3,8)
G.add_edge(4,12)
G.add_edge(5,9)
G.add_edge(6,10)
G.add_edge(7,11)
G.add_edge(8,12)
G.add_edge(9,13)
G.add_edge(10,14)
G.add_edge(11,16)
G.add_edge(12,15)
G.add_edge(13,17)
G.add_edge(14,16)
G.add_edge(15,17)
G.add_edge(16,17)


color_map=[]
pos = nx.spring_layout(G, seed=5, k=0.7*1/np.sqrt(len(G.nodes())), iterations=20)
attr_list=G.nodes(data='color')
for attr in attr_list:
    color_map.append(attr[1])
nx.draw_networkx(G,pos,with_labels=True,node_color=color_map, labels = {n: str(n) + ';' + str(G.nodes[n]['weight']) for n in G.nodes}, node_size=500)
plt.savefig('output/graph_paper.png')
plt.show()
nx.write_gpickle(G,'output/graph.gpickle')
